### ISSUE TITLE
Lacking ability to utilize Lubricating Oil in Chemical Slot on Final Combine of Harvesters

### ISSUE THREAD

**Issue by XaviousD** [twistedatrocity/SWGAide-NGE#18]
In The Laboratory i'm playing around to see what i can achieve and I've noticed I cannot utilize Lubricating Oil in the chemical slot of the final combine.  This is easily seen on the Elite Deep Crust Chemical Extractor.

Utilizing lubricating oil in many of the chemical resource spots in nice because it doesn't have the stats utilized in the Extraction Rate/Hopper Size calculations so its ignored.

**Comment by twistedatrocity** [comment]
It's because the schematic calls for HQ... and the lube oil is literally a 0.00 rating thus there is really no way to sort or pull into the list if you have resources that match any of the stats as those will have a rating higher than 0

It will show if one has no statted resources for that slot (or less than the number of resources you are choosing to show).

Maybe a toggle to show only no rating res or something, I'm not sure how that would work out though.

**Comment by twistedatrocity** [comment]
I've increased the amount of resources limit to 50 in [Release 0.1.23](https://github.com/twistedatrocity/SWGAide-NGE/releases/tag/v.0.1.23)
This should help to alleviate the issue for now. I have been thinking of completely redesigning that panel.
Going to go ahead and close this now. If you think it needs bumped higher feel free to open another issue, or let me know here.
