### ISSUE TITLE
Resource Inventory Screen Causes GUI artifacts and duplication

### ISSUE THREAD

**Issue by nathanklick** [twistedatrocity/SWGAide-NGE#28]
While running on Windows 10 under Oracle Java `1.8.0_311` the GUI has major artifacts that render it unusable. See steps to reproduce and screenshot below. This issue happens under all three themes.

## Steps to Reproduce
- Click the Add button to add a new resource to the inventory
- Select the character drop down menu 
- Artifacts begin after using the drop down menu to select the owning character
 

```
java version "1.8.0_311"
Java(TM) SE Runtime Environment (build 1.8.0_311-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.311-b11, mixed mode)
```

![image](https://user-images.githubusercontent.com/7484611/140001730-8abf6543-cb14-4f0e-b5cc-4c2edd98a5ff.png)

**Comment by twistedatrocity** [comment]
This is generally a graphics memory issue. I cannot reproduce this on a clean system, however I have noticed it occur when I have 3 instances of swg running and swgaide running at the same time. Are you running multiple swg's while running swgaide? Or other things open that are using graphics memory?

**Comment by nathanklick** [comment]
It is reproducible within seconds of opening the add a resource to inventory pop-up window without anything other than SWGAide-Unity and Google Chrome running. 

My system has 32 GB of DDR4 RAM and Nvidia GeForce 1080Ti Founders Edition GPU. Closing and reopening SWGAide doesn't help as the problem happens as soon as I return to the add screen in resource inventory. 

What's weird is that I can use the current resources tab and the used-by-schematic pop-up for over an hour with no issue. I can also use the entire schematics tab without any issue for the same amount of time. 

The resource inventory tab immediately produces the problem.

**Comment by nathanklick** [comment]
Using this dropdown list immediately triggers the problem:

![image](https://user-images.githubusercontent.com/7484611/140005600-65004aa4-469c-4a7d-b69b-d98206ad7982.png)

**Comment by twistedatrocity** [comment]
This is not reproducible for me on any of my machines, it has only ever happened at random when I have multi swg instances running on an old laptop with Win7.

It is not a bug with swgaide code as there is no direct painting from the code, it is an issue with Java itself and/or windows, and the graphics card driver.

See here for further details: https://stackoverflow.com/questions/21681071/java-swing-screen-artifacts

You could try the opengl flag mentioned in the answer to the above, launching the JAR file from command line instead of the exe.  e.g. cd to the directory you have saved the jar and run:   javaw -Dsun.java2d.opengl=true -jar SWGAide-Unity.jar

**Comment by nathanklick** [comment]
@twistedatrocity Adding the JVM option `-Dsun.java2d.opengl=true` solved the issue.
