### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by HydroTek** [twistedatrocity/SWGAide-NGE#5]
With the high rez monitors of today, it would be cool to make an option to increase the font size ...unless that would break the GUI

**Comment by twistedatrocity** [comment]
Just realized you had opened issues.... no email from github, sorry for the late reply.

Will look into it when I get time.

**Comment by twistedatrocity** [comment]
Just wanted to follow up on this, I did not forget.

I have looked into this a couple times now... With the way the aide GUI is written, it will not be possible without rewriting a very good portion of the GUI. Mainly because most elements are statically sized and increasing font would push text beyond element borders making it unreadable. All of the table elements (which accounts for most of the views) are static also.

So short answer is it won't be a quick and easy task.

**Comment by twistedatrocity** [comment]
Font sizing added in 0.1.12  https://github.com/twistedatrocity/SWGAide-NGE/tree/v.0.1.12
